Add MPI backend
nums-project/nums pull request #271
Opened 2022-02-15 18:38 UTC by vinamrabenara

2022-02-18 16:52 UTC, closed without merging

2022-02-18 17:30 UTC, elibol requested changes
Looking good. Can we add a small section in `README.md` on dependencies needed to use MPI backend? Also a very small code snippet that configures nums to use the MPI backend, plus the CL to execute it.

2022-02-18 17:30 UTC, elibol commented on .github/workflows/test.yml
> +      - name: Run MPI tests
Can we hold off on adding MPI testing until we have nightly builds? As-is, this will increase test time significantly.

2022-02-18 17:30 UTC, elibol commented on nums/core/array/application.py
> +        total_size = sum(self.cm.get(s_oids))
Please open a separate PR to make this change.

2022-02-18 17:30 UTC, elibol commented on nums/core/systems/systems.py
> +        # TODO: sort proc_names and dont do a all gather for did. construct them locally
Grammar [nit].

2022-02-18 17:30 UTC, elibol commented on nums/core/systems/systems.py
> +            # func_return = []
Remove commented code.

2022-02-18 17:30 UTC, elibol commented on nums/core/systems/systems.py
> +    def _resolve_args_or_kwargs(
Refactor to have 2 separate functions, one for `args` and one for `kwargs`.

2022-02-18 17:30 UTC, elibol commented on nums/core/systems/systems.py
> +        resolved_args = self._resolve_args_or_kwargs(args, dest_rank)
Also resolve `kwargs` here.

2022-02-18 17:30 UTC, elibol commented on tests/core/test_app_manager.py
> +        pass
Let's update this to assert `app.cm.num_cores_total()` is equal to mpi size.

2022-02-18 17:30 UTC, elibol commented on tests/numpy/test_np_stats.py
> +    # from mpi4py import MPI
Please remove commented code. This does look useful for MPI debugging, though. Can we make a note of this and add documentation to contributor section on how to properly debug MPI?

2022-02-19 06:02 UTC, elibol approved these changes
LGTM! Tested locally and looks good. Let's not forget to open a separate PR to add how to test with pytest and debug with pycharm (would go under contributing documentation)!

2022-02-19 07:10 UTC, vinamrabenara commented
> LGTM! Tested locally and looks good. Let's not forget to open a separate PR to add how to test with pytest and debug with pycharm (would go under contributing documentation)!

yes! i created an issue for that #279